# Create directory
mkdir .streamlit

# Create config file
echo "[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = '#667eea'
backgroundColor = '#ffffff'
secondaryBackgroundColor = '#f0f2f6'
textColor = '#262730'
font = 'sans serif'" > .streamlit/config.toml